[workspace]
package = { version = "0.0.6", categories = ["HTTP client", "Procedural macro helpers"] }
members = ["clientix", "clientix-codegen", "clientix-core", "clientix-example"]
resolver = "2"

[workspace.dependencies]
clientix = { path = "clientix", version = "0.0.6" }
clientix-core = { path = "clientix-core", version = "0.0.6" }
clientix-codegen = { path = "clientix-codegen", version = "0.0.6" }