[package]
name = "clientix-example"
version = "0.1.0"
edition = "2021"

[dependencies]
clientix = { path = "../clientix" }
tokio = { version = "1.47.1", features = ["full"] }
uuid = { version = "1.18.0", features = ["v4"] }