[package]
version.workspace = true
categories.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
publish = false

name = "clientix-example"

[dependencies]
clientix = { workspace = true }
tokio = "1.47.1"

[features]
default = ["std"]
std = ["tokio/full"]
