[registry]
global-credential-providers = ["cargo:token"]

[registries]
cargo-crates = { index = "sparse+https://index.crates.io/" }
cargo-group = { index = "sparse+https://registry.xslab.ltd/repository/cargo-group/" }
cargo-releases = { index = "sparse+https://registry.xslab.ltd/repository/cargo-releases/" }
cargo-snapshots = { index = "sparse+https://registry.xslab.ltd/repository/cargo-snapshots/" }

[source.crates-io]
replace-with = "cargo-group"